### ISSUE TITLE
Sanitizer common options can be overwritten by other sanitizer's default option

### ISSUE THREAD

**Issue by junwha** [AFLplusplus/AFLplusplus#1624]
### Discussed in https://github.com/AFLplusplus/AFLplusplus/discussions/1618

The above problem was not the behaviour in asan, but it was sanitizer cmmon flag overwritten problem.

in [src/afl-forkserver.c](https://github.com/AFLplusplus/AFLplusplus/blob/3b6fcd911a860a8c823c912c4b08b423734e4cfe/src/afl-forkserver.c#L693), afl++ set `abort_on_error` and `symbolize` for all the four sanitizer flags, ASAN_OPTIONS, LSAN_OPTIONS, MSAN_OPTIONS, and UBSAN OPTIONS.

And it is problematic because the four sanitizers internally share the [sanitizer common options](https://github.com/google/sanitizers/wiki/SanitizerCommonFlags). For this reason, my ASAN_OPTION=abort_on_error=1:symbolize=1 has been overwritten by three sanitizer's other options.

In my case, symbolize=1 was discouraged by AFL++, thus it can be considered as a trivial problem.
But I think this implementation is something that needs to be fixed because what the user has set up in one sanitizer has a potential risk of overwriting by AFL++ initialization.

**Comment by vanhauser-thc** [comment]
it is not overwritten:
```
    if (!getenv("ASAN_OPTIONS"))
      setenv("ASAN_OPTIONS",
```
it is only set if no env is set for it.

**Comment by vanhauser-thc** [comment]
ah now I understand what you mean.
hmm which of the 4 sanitizers options take precedence then?

**Comment by vanhauser-thc** [comment]
can you have a look at 90a259d5231242562d3cb2e62f2c8cdbf073b3a0 please?

**Comment by junwha** [comment]
Now it works as expected!:)

FYI, there are more codes that share this feature

[src/afl-showmap.c#L596](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-showmap.c#L596)
[src/afl-tmin.c#L643](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-tmin.c#L643)
[utils/afl_network_proxy/afl-network-server.c#L157](https://github.com/AFLplusplus/AFLplusplus/blob/stable/utils/afl_network_proxy/afl-network-server.c#L157)
[src/afl-analyze.c#L627](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-analyze.c#L627)
[src/afl-tmin.c#L643](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-tmin.c#L643)

Thank you much!

**Comment by vanhauser-thc** [comment]
uh right.
if you can have a quick look if this looks good please? f4a13585a1a205798093291fd04659a4158b4d50

**Comment by junwha** [comment]
it's now all good!😃

**Comment by vanhauser-thc** [comment]
thanks!

**Comment by LexPanov** [comment]
Hey, I think you've killed LSAN usage in this commit

Example C program with leak:

```c
// /test/test_lsan.c

#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{
    int n;
    void *p;
    scanf("%d", &n);
    printf("\nYou entered: %d\n", n);
    if (n != 0)
    {
        printf("Starting leak...\n");
        p = malloc(10);
        p = 0;
        printf("Leaked\n");
        return 1;
    }
    printf("Nothing to fail\n");
    return 0;
}
```

Compiled with `AFL_USE_LSAN=1` leaks if we execute it manually

```sh
❯ docker run -v $(pwd):/test --rm -it aflplusplus/aflplusplus:stable bash
[afl++ 3c596e9d4ae7] /AFLplusplus # cd /test
[afl++ 3c596e9d4ae7] /test # AFL_USE_LSAN=1 afl-clang-lto -O0 -g test_lsan.c -o test_lsan
afl-cc++4.06a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-LTO-PCGUARD
afl-llvm-lto++4.06a by Marc "vanHauser" Heuse <mh@mh-sec.de>
[+] Instrumented 2 locations (0 selects) without collisions (0 collisions have been avoided) (non-hardened mode).
[afl++ 3c596e9d4ae7] /test # echo 0 | ./test_lsan
You entered: 0
Nothing to fail
[afl++ 3c596e9d4ae7] /test # echo 1 | ./test_lsan
You entered: 1
Starting leak...
Leaked

=================================================================
==603==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 10 byte(s) in 1 object(s) allocated from:
    #0 0x5cc0c89a5532 in malloc (/test/test_lsan+0x47532) (BuildId: 90881b84791848b7)
    #1 0x5cc0c89abb24 in main /test/test_lsan.c:15:13
    #2 0x7cca86381d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)

SUMMARY: LeakSanitizer: 10 byte(s) leaked in 1 allocation(s).
```

But if we start `aflplusplus/aflplusplus:stable` - nothing found

```sh
[afl++ 3c596e9d4ae7] /test # mkdir in && echo 0 > in/0
[afl++ 3c596e9d4ae7] /test # AFL_BENCH_JUST_ONE=1 afl-fuzz -D -i in -o out -- ./test_lsan
[+] Enabled environment variable AFL_BENCH_JUST_ONE with value 1
[+] Enabled environment variable AFL_SKIP_CPUFREQ with value 1
[+] Enabled environment variable AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES with value 1
[+] Enabled environment variable AFL_TRY_AFFINITY with value 1

           american fuzzy lop ++4.06a {default} (./test_lsan) [fast]
┌─ process timing ────────────────────────────────────┬─ overall results ────┐
│        run time : 0 days, 0 hrs, 0 min, 0 sec       │  cycles done : 0     │
│   last new find : 0 days, 0 hrs, 0 min, 0 sec       │ corpus count : 2     │
│last saved crash : none seen yet                     │saved crashes : 0     │
│ last saved hang : none seen yet                     │  saved hangs : 0     │
├─ cycle progress ─────────────────────┬─ map coverage┴──────────────────────┤
│  now processing : 0.1 (0.0%)         │    map density : 11.11% / 22.22%    │
│  runs timed out : 0 (0.00%)          │ count coverage : 209.00 bits/tuple  │
├─ stage progress ─────────────────────┼─ findings in depth ─────────────────┤
│  now trying : havoc                  │ favored items : 1 (50.00%)          │
│ stage execs : 800/800 (100.00%)      │  new edges on : 2 (100.00%)         │
│ total execs : 1036                   │ total crashes : 0 (0 saved)         │
│  exec speed : 4637/sec               │  total tmouts : 0 (0 saved)         │
├─ fuzzing strategy yields ────────────┴─────────────┬─ item geometry ───────┤
│   bit flips : 1/16, 0/15, 0/13                     │    levels : 2         │
│  byte flips : 0/2, 0/1, 0/0                        │   pending : 1         │
│ arithmetics : 0/112, 0/25, 0/0                     │  pend fav : 0         │
│  known ints : 0/9, 0/28, 0/0                       │ own finds : 1         │
│  dictionary : 0/0, 0/0, 0/0, 0/0                   │  imported : 0         │
│havoc/splice : 0/800, 0/0                           │ stability : 100.00%   │
│py/custom/rq : unused, unused, unused, unused       ├───────────────────────┘
│    trim/eff : n/a, 0.00%                           │          [cpu000: 50%]
└────────────────────────────────────────────────────┘

+++ Testing aborted by user +++
[+] We're done here. Have a nice day!
```

Although if the same steps are repeated in `aflplusplus/aflplusplus:4.05c` it works just fine

```sh
❯ docker run -v $(pwd):/test --rm -it aflplusplus/aflplusplus:4.05c bash
[afl++ 67a8e3497965] /AFLplusplus # cd /test 
[afl++ 67a8e3497965] /test # AFL_USE_LSAN=1 afl-clang-lto -O0 -g test_lsan.c -o test_lsan
afl-cc++4.05c by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-LTO-PCGUARD
afl-llvm-lto++4.05c by Marc "vanHauser" Heuse <mh@mh-sec.de>
[+] Instrumented 2 locations (0 selects) without collisions (0 collisions have been avoided) (non-hardened mode).
[afl++ 67a8e3497965] /test # AFL_BENCH_JUST_ONE=1 afl-fuzz -D -i in -o out -- ./test_lsan
[+] Enabled environment variable AFL_BENCH_JUST_ONE with value 1
[+] Enabled environment variable AFL_SKIP_CPUFREQ with value 1
[+] Enabled environment variable AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES with value 1
[+] Enabled environment variable AFL_TRY_AFFINITY with value 1
afl-fuzz++4.05c based on afl by Michal Zalewski and a large online community
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Eißfeldt, Andrea Fioraldi and Dominik Maier
[+] afl++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
[+] NOTE: This is v3.x which changes defaults and behaviours - see README.md

           american fuzzy lop ++4.05c {default} (./test_lsan) [fast]
┌─ process timing ────────────────────────────────────┬─ overall results ────┐
│        run time : 0 days, 0 hrs, 0 min, 9 sec       │  cycles done : 0     │
│   last new find : none seen yet                     │ corpus count : 1     │
│last saved crash : 0 days, 0 hrs, 0 min, 9 sec       │saved crashes : 1     │
│ last saved hang : none seen yet                     │  saved hangs : 0     │
├─ cycle progress ─────────────────────┬─ map coverage┴──────────────────────┤
│  now processing : 0.1 (0.0%)         │    map density : 11.11% / 11.11%    │
│  runs timed out : 0 (0.00%)          │ count coverage : 417.00 bits/tuple  │
├─ stage progress ─────────────────────┼─ findings in depth ─────────────────┤
│  now trying : havoc                  │ favored items : 1 (100.00%)         │
│ stage execs : 512/512 (100.00%)      │  new edges on : 1 (100.00%)         │
│ total execs : 741                    │ total crashes : 579 (1 saved)       │
│  exec speed : 76.34/sec (slow!)      │  total tmouts : 0 (0 saved)         │
├─ fuzzing strategy yields ────────────┴─────────────┬─ item geometry ───────┤
│   bit flips : 1/16, 0/15, 0/13                     │    levels : 1         │
│  byte flips : 0/2, 0/1, 0/0                        │   pending : 0         │
│ arithmetics : 0/112, 0/25, 0/0                     │  pend fav : 0         │
│  known ints : 0/9, 0/28, 0/0                       │ own finds : 0         │
│  dictionary : 0/0, 0/0, 0/0, 0/0                   │  imported : 0         │
│havoc/splice : 0/512, 0/0                           │ stability : 100.00%   │
│py/custom/rq : unused, unused, unused, unused       ├───────────────────────┘
│    trim/eff : n/a, 0.00%                           │          [cpu000: 37%]
└────────────────────────────────────────────────────┘

+++ Testing aborted by user +++
[+] We're done here. Have a nice day!
```

Analyzing this function
https://github.com/AFLplusplus/AFLplusplus/blob/f4a13585a1a205798093291fd04659a4158b4d50/src/afl-common.c#L61-L116

I found, that `LSAN_OPTIONS` while running afl differs

version 4.05c - image `aflplusplus/aflplusplus:4.05c` - old, working behaviour:

```sh
ASAN_OPTIONS=abort_on_error=1:detect_leaks=0:malloc_context_size=0:symbolize=0:allocator_may_return_null=1:detect_odr_violation=0:handle_segv=0:handle_sigbus=0:handle_abort=0:handle_sigfpe=0:handle_sigill=0
UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:malloc_context_size=0:allocator_may_return_null=1:symbolize=0:handle_segv=0:handle_sigbus=0:handle_abort=0:handle_sigfpe=0:handle_sigill=0
MSAN_OPTIONS=exit_code=86:symbolize=0:abort_on_error=1:malloc_context_size=0:allocator_may_return_null=1:msan_track_origins=0:handle_segv=0:handle_sigbus=0:handle_abort=0:handle_sigfpe=0:handle_sigill=0
LSAN_OPTIONS=exitcode=23:fast_unwind_on_malloc=0:symbolize=0:print_suppressions=0
```

version 4.06a - image `aflplusplus/aflplusplus:stable` - new, breaking behaviour:

```sh
ASAN_OPTIONS=detect_odr_violation=0:abort_on_error=1:symbolize=0:malloc_context_size=0:allocator_may_return_null=1:handle_segv=0:handle_sigbus=0:handle_abort=0:handle_sigfpe=0:handle_sigill=0:detect_leaks=0:
UBSAN_OPTIONS=detect_odr_violation=0:abort_on_error=1:symbolize=0:malloc_context_size=0:allocator_may_return_null=1:handle_segv=0:handle_sigbus=0:handle_abort=0:handle_sigfpe=0:handle_sigill=0:detect_leaks=0:
MSAN_OPTIONS=detect_odr_violation=0:abort_on_error=1:symbolize=0:malloc_context_size=0:allocator_may_return_null=1:handle_segv=0:handle_sigbus=0:handle_abort=0:handle_sigfpe=0:handle_sigill=0:detect_leaks=0:exit_code=86:msan_track_origins=0:
LSAN_OPTIONS=detect_odr_violation=0:abort_on_error=1:symbolize=0:malloc_context_size=0:allocator_may_return_null=1:handle_segv=0:handle_sigbus=0:handle_abort=0:handle_sigfpe=0:handle_sigill=0:detect_leaks=0:exitcode=23:fast_unwind_on_malloc=0:print_suppressions=0:
```

Here we can see, that `LSAN_OPTIONS` is initialized with `malloc_context_size=0` and `detect_leaks=0` that literally disables LSAN leak detection

If afl is started with default for LSAN `malloc_context_size=30` and `detect_leaks=1` it works

```sh
❯ docker run -v $(pwd):/test --rm -it aflplusplus/aflplusplus:stable bash
[afl++ 3c596e9d4ae7] /AFLplusplus # cd /test
[afl++ 3c596e9d4ae7] /test # AFL_USE_LSAN=1 afl-clang-lto -O0 -g test_lsan.c -o test_lsan
afl-cc++4.06a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-LTO-PCGUARD
afl-llvm-lto++4.06a by Marc "vanHauser" Heuse <mh@mh-sec.de>
[+] Instrumented 2 locations (0 selects) without collisions (0 collisions have been avoided) (non-hardened mode).
[afl++ 3c596e9d4ae7] /test # LSAN_OPTIONS=detect_odr_violation=0:abort_on_error=1:symbolize=0:malloc_context_size=30:allocator_may_return_null=1:handle_segv=0:handle_sigbus=0:handle_abort=0:handle_sigfpe=0:handle_sigill=0:detect_leaks=1:exitcode=23:fast_unwind_on_malloc=0:print_suppressions=0: AFL_BENCH_JUST_ONE=1 afl-fuzz -D -i in -o out -- ./test_lsan
[+] Enabled environment variable AFL_BENCH_JUST_ONE with value 1
[+] Enabled environment variable AFL_SKIP_CPUFREQ with value 1
[+] Enabled environment variable AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES with value 1
[+] Enabled environment variable AFL_TRY_AFFINITY with value 1
afl-fuzz++4.06a based on afl by Michal Zalewski and a large online community
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Eißfeldt, Andrea Fioraldi and Dominik Maier
[+] afl++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
[+] NOTE: This is v3.x which changes defaults and behaviours - see README.md
[+] Enabled environment variable LSAN_OPTIONS with value detect_odr_violation=0:abort_on_error=1:symbolize=0:malloc_context_size=30:allocator_may_return_null=1:handle_segv=0:handle_sigbus=0:handle_abort=0:handle_sigfpe=0:handle_sigill=0:detect_leaks=1:exitcode=23:fast_unwind_on_malloc=0:print_suppressions=0:
[+] No -M/-S set, autoconfiguring for "-S default"
[*] Getting to work...

           american fuzzy lop ++4.06a {default} (./test_lsan) [fast]
┌─ process timing ────────────────────────────────────┬─ overall results ────┐
│        run time : 0 days, 0 hrs, 0 min, 8 sec       │  cycles done : 0     │
│   last new find : none seen yet                     │ corpus count : 1     │
│last saved crash : 0 days, 0 hrs, 0 min, 8 sec       │saved crashes : 1     │
│ last saved hang : none seen yet                     │  saved hangs : 0     │
├─ cycle progress ─────────────────────┬─ map coverage┴──────────────────────┤
│  now processing : 0.1 (0.0%)         │    map density : 11.11% / 11.11%    │
│  runs timed out : 0 (0.00%)          │ count coverage : 417.00 bits/tuple  │
├─ stage progress ─────────────────────┼─ findings in depth ─────────────────┤
│  now trying : havoc                  │ favored items : 1 (100.00%)         │
│ stage execs : 400/400 (100.00%)      │  new edges on : 1 (100.00%)         │
│ total execs : 629                    │ total crashes : 478 (1 saved)       │
│  exec speed : 76.16/sec (slow!)      │  total tmouts : 0 (0 saved)         │
├─ fuzzing strategy yields ────────────┴─────────────┬─ item geometry ───────┤
│   bit flips : 1/16, 0/15, 0/13                     │    levels : 1         │
│  byte flips : 0/2, 0/1, 0/0                        │   pending : 0         │
│ arithmetics : 0/112, 0/25, 0/0                     │  pend fav : 0         │
│  known ints : 0/9, 0/28, 0/0                       │ own finds : 0         │
│  dictionary : 0/0, 0/0, 0/0, 0/0                   │  imported : 0         │
│havoc/splice : 0/400, 0/0                           │ stability : 100.00%   │
│py/custom/rq : unused, unused, unused, unused       ├───────────────────────┘
│    trim/eff : n/a, 0.00%                           │          [cpu000: 25%]
└────────────────────────────────────────────────────┘

+++ Testing aborted by user +++
[+] We're done here. Have a nice day!
```

**Comment by vanhauser-thc** [comment]
I have never used lsan. 
the goal is that leaks are only triggering crashes if a target is compiled with LSAN, but not when compiled with ASAN.
can you try if the current dev state works?
I sadly have very very little time at the moment :-(

**Comment by LexPanov** [comment]
There is still `malloc_context_size=0` because of
https://github.com/AFLplusplus/AFLplusplus/blob/dc7ef967d8dd4a338ddc72b41dcf8840437aabc2/src/afl-common.c#L69-L71

It should be `malloc_context_size=30` for LSAN to work, as metioned here https://github.com/google/sanitizers/wiki/SanitizerCommonFlags#:~:text=handle%20ioctl%20requests.-,malloc_context_size,-30

And here
https://github.com/gcc-mirror/gcc/blob/a6457974a1f443ab58d2334c02260299616c78b8/libsanitizer/lsan/lsan.cpp#L58

**Comment by LexPanov** [comment]
Maybe such patch will be correct

```patch
diff --git a/src/afl-common.c b/src/afl-common.c
index b0df1994..48b9b914 100644
--- a/src/afl-common.c
+++ b/src/afl-common.c
@@ -67,8 +67,8 @@ void set_sanitizer_defaults() {
   u8 *have_lsan_options = getenv("LSAN_OPTIONS");
   u8  have_san_options = 0;
   u8  default_options[1024] =
-      "detect_odr_violation=0:abort_on_error=1:symbolize=0:malloc_context_"
-      "size=0:allocator_may_return_null=1:handle_segv=0:handle_sigbus=0:"
+      "detect_odr_violation=0:abort_on_error=1:symbolize=0:"
+      "allocator_may_return_null=1:handle_segv=0:handle_sigbus=0:"
       "handle_abort=0:handle_sigfpe=0:handle_sigill=0:";
 
   if (have_asan_options || have_ubsan_options || have_msan_options ||
@@ -91,7 +91,7 @@ void set_sanitizer_defaults() {
 
   /* for everything not LSAN we disable detect_leaks */
 
-  if (!have_lsan_options) { strcat(default_options, "detect_leaks=0:"); }
+  if (!have_lsan_options) { strcat(default_options, "malloc_context_size=0:detect_leaks=0:"); }
 
   /* Set sane defaults for ASAN if nothing else is specified. */
```

**Comment by vanhauser-thc** [comment]
OK, please try again :-)

**Comment by LexPanov** [comment]
Yes, now it's OK, thank you!

Binary, compiled with ASAN gives no crashes, LSAN crashes just fine.
*SAN options look like this for https://github.com/AFLplusplus/AFLplusplus/commit/5221938945cc5ff15af04b727c6a7e0085005044:

```
[afl++ 4ed19490ee7d] /AFLplusplus # ps faux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     29951 11.5  0.0 160792 29432 pts/0    S+   17:02   0:01 afl-fuzz -D -i in -o out -- ./test_lsan
root     29952 21.8  0.0  12904  1400 ?        Ss   17:02   0:02  \_ ./test_lsan
[afl++ 4ed19490ee7d] /AFLplusplus # strings /proc/29952/environ | egrep ".*_OPTIONS"
LSAN_OPTIONS=detect_odr_violation=0:abort_on_error=1:symbolize=0:allocator_may_return_null=1:handle_segv=0:handle_sigbus=0:handle_abort=0:handle_sigfpe=0:handle_sigill=0:exitcode=23:fast_unwind_on_malloc=0:print_suppressions=0:detect_leaks=1:malloc_context_size=30:
ASAN_OPTIONS=detect_odr_violation=0:abort_on_error=1:symbolize=0:allocator_may_return_null=1:handle_segv=0:handle_sigbus=0:handle_abort=0:handle_sigfpe=0:handle_sigill=0:detect_leaks=0:malloc_context_size=0:
UBSAN_OPTIONS=detect_odr_violation=0:abort_on_error=1:symbolize=0:allocator_may_return_null=1:handle_segv=0:handle_sigbus=0:handle_abort=0:handle_sigfpe=0:handle_sigill=0:detect_leaks=0:malloc_context_size=0:
MSAN_OPTIONS=detect_odr_violation=0:abort_on_error=1:symbolize=0:allocator_may_return_null=1:handle_segv=0:handle_sigbus=0:handle_abort=0:handle_sigfpe=0:handle_sigill=0:detect_leaks=0:malloc_context_size=0:exit_code=86:msan_track_origins=0:
```

| Option                    | LSAN | ASAN | UBSAN | MSAN |
|---------------------------|------|------|-------|------|
| detect_odr_violation      |    0 |    0 |     0 |    0 |
| abort_on_error            |    1 |    1 |     1 |    1 |
| symbolize                 |    0 |    0 |     0 |    0 |
| allocator_may_return_null |    1 |    1 |     1 |    1 |
| handle_segv               |    0 |    0 |     0 |    0 |
| handle_sigbus             |    0 |    0 |     0 |    0 |
| handle_abort              |    0 |    0 |     0 |    0 |
| handle_sigfpe             |    0 |    0 |     0 |    0 |
| handle_sigill             |    0 |    0 |     0 |    0 |
| exitcode                  |   23 | -    | -     |   86 |
| detect_leaks              |    1 |    0 |     0 |    0 |
| malloc_context_size       |   30 |    0 |     0 |    0 |
| fast_unwind_on_malloc     |    0 | -    | -     | -    |
| print_suppressions        |    0 | -    | -     | -    |
| msan_track_origins        | -    | -    | -     |    0 |

**Comment by vanhauser-thc** [comment]
thank you!
