### ISSUE TITLE
LSAN not working when running afl-fuzz on binaries compiled with -fsanitize=fuzzer 

### ISSUE THREAD

**Issue by petitnau** [AFLplusplus/AFLplusplus#1827]
I am not able to get any leaks reported when using `afl-fuzz` on binaries compiled with `-fsanitize=fuzzer`.

Here is a minimal example:
```c
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
 
int LLVMFuzzerTestOneInput(uint8_t * data, size_t size)
{
    char *x = (char*)malloc(10 * sizeof(char*));
    if (data[0] != 'X') 
        free(x);
    return 0;
}

```
If I run `AFL_USE_LSAN=1 afl-clang-lto -O0 test.c -o test -fsanitize=fuzzer && ./test empty_file`, I am able to get an error reported
```bash[afl++ e3e8cac4ae95] /test # ./test x_file 
Reading 2 bytes from random_file
Execution successful.

=================================================================
==26==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x56288da05ed2 in malloc (/test/test+0x47ed2) (BuildId: 1770443c5f523dce)
    #1 0x56288da0ca29 in LLVMFuzzerTestOneInput /test/test.c:8:22
    #2 0x56288da08ced in ExecuteFilesOnyByOne /AFLplusplus/utils/aflpp_driver/aflpp_driver.c:240:7

SUMMARY: LeakSanitizer: 80 byte(s) leaked in 1 allocation(s).
```

If however, I run the executable with afl-fuzz, I get no crashes
```bash
[AFL++ e3e8cac4ae95] /test # afl-fuzz -i in -o out -d -- ./test
...
             american fuzzy lop ++4.08a {default} (./test) [fast]
┌─ process timing ────────────────────────────────────┬─ overall results ────┐
│        run time : 0 days, 0 hrs, 0 min, 13 sec      │  cycles done : 630   │
│   last new find : 0 days, 0 hrs, 0 min, 13 sec      │ corpus count : 2     │
│last saved crash : none seen yet                     │saved crashes : 0     │
│ last saved hang : none seen yet                     │  saved hangs : 0     │
├─ cycle progress ─────────────────────┬─ map coverage┴──────────────────────┤
│  now processing : 1.2006 (50.0%)     │    map density : 22.22% / 33.33%    │
│  runs timed out : 0 (0.00%)          │ count coverage : 139.67 bits/tuple  │
├─ stage progress ─────────────────────┼─ findings in depth ─────────────────┤
│  now trying : havoc                  │ favored items : 2 (100.00%)         │
│ stage execs : 1/345 (0.29%)          │  new edges on : 2 (100.00%)         │
│ total execs : 870k                   │ total crashes : 0 (0 saved)         │
│  exec speed : 65.9k/sec              │  total tmouts : 0 (0 saved)         │
├─ fuzzing strategy yields ────────────┴─────────────┬─ item geometry ───────┤
│   bit flips : disabled (default, enable with -D)   │    levels : 2         │
│  byte flips : disabled (default, enable with -D)   │   pending : 0         │
│ arithmetics : disabled (default, enable with -D)   │  pend fav : 0         │
│  known ints : disabled (default, enable with -D)   │ own finds : 1         │
│  dictionary : n/a                                  │  imported : 0         │
│havoc/splice : 1/870k, 0/0                          │ stability : 100.00%   │
│py/custom/rq : unused, unused, unused, unused       ├───────────────────────┘
│    trim/eff : 33.33%/1, disabled                   │          [cpu000: 50%]
└─ strategy: explore ────────── state: started :-) ──┘^C

+++ Testing aborted by user +++
[+] We're done here. Have a nice day!

```

The issue seems related to #1624, where the same problem occurred with binaries compiled in general.

**Comment by devnexen** [comment]
would [the doc](https://github.com/AFLplusplus/AFLplusplus/blob/fa44d8f79f03c0aab3cfea93c37b70edc367c1bb/docs/fuzzing_in_depth.md?plain=1#L226) help you ?

**Comment by petitnau** [comment]
> would [the doc](https://github.com/AFLplusplus/AFLplusplus/blob/fa44d8f79f03c0aab3cfea93c37b70edc367c1bb/docs/fuzzing_in_depth.md?plain=1#L226) help you ?

Thanks for the answer. Adding a call to `AFL_LEAK_CHECK` did not change the result, but I did some more testing and figured out the problem was a bit different than what I was seemingly getting. I updated the issue to reflect that.

**Comment by vanhauser-thc** [comment]
it is because you do not tell the leak sanitizer to abort on leaks or tell afl-fuzz to look for the specific error number it exits with. it is just exiting with an error.

**Comment by petitnau** [comment]
> it is because you do not tell the leak sanitizer to abort on leaks or tell afl-fuzz to look for the specific error number it exits with. it is just exiting with an error.

Is that something that must be done specifically when binaries are compiled with `-fsanitize=fuzzer`? If yes, is there any chance you could reference the docs that explain how to solve this problem?

If not, note that when wrapping with a `main` and not compiling with `-fsanitize=fuzzer`, the error is always detected
```c
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
 
int LLVMFuzzerTestOneInput(uint8_t *data, size_t size)
{
    char *x = (char*)malloc(10 * sizeof(char*));
    if (data[0] == '0') 
        free(x);
    return 0;
}

int main(int argc, char* argv[]) {
    uint8_t c;
    scanf("%c", &c);

    LLVMFuzzerTestOneInput(&c, 1);
}
```

```bash
AFL_USE_LSAN=1 afl-clang-lto -O0 test.c -o test;
echo 1 | ./test; # Leak is detected
afl-fuzz -D -i in -o out -- ./test # Leak is detected
```

And when compiling with `-fsanitize=fuzzer`, the error is not detected with `afl-fuzz`
```c
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
 
int LLVMFuzzerTestOneInput(uint8_t *data, size_t size)
{
    char *x = (char*)malloc(10 * sizeof(char*));
    if (data[0] == '0') 
        free(x);
    return 0;
}
```

```bash
AFL_USE_LSAN=1 afl-clang-lto -O0 test.c -o test -fsanitize=fuzzer;
echo 1 > 1 && ./test 1; # Leak is detected
afl-fuzz -D -i in -o out -- ./test # Leak is NOT detected
```

**Comment by vanhauser-thc** [comment]
look in the docs for `AFL_CRASH_EXITCODE`:

and this is the preconfigured error code:
```
include/config.h:#define LSAN_ERROR 23
src/afl-common.c:    strcat(buf, "exitcode=" STRINGIFY(LSAN_ERROR) ":fast_unwind_on_malloc=0:print_suppressions=0:detect_leaks=1:malloc_context_size=30:");
```

if you find the documention for lsan weak (in my opinion it is, but honestly it is something very very few users use afl-fuzz for) then feel free to send a PR.

Why -fsanitize=fuzzer does not produce a crash and without it it does I do not know, it makes no sense to me. all -fsanitize=fuzzer does it adding the object file of utils/aflpp_driver/aflpp_driver.c which is similar to your main().
