### ISSUE TITLE
Nyx assertion `left == right` failed at src/ffi.rs:97:5 with afl-cmin

### ISSUE THREAD

**Issue by choller** [AFLplusplus/AFLplusplus#2155]
This commit changed behavior to pass `fsrv->max_length` to Nyx instead of `MAX_FILE`:

https://github.com/AFLplusplus/AFLplusplus/commit/ab36756061b52c8f6bf5d4650ebf42d7c31d8cd9

However, when running `afl-showmap` (indirectly through `afl-cmin`), then `fsrv->max_length` is not set and we end up with an assertion:

```
corpus minimization tool for AFL++ (awk version)
[...]
[+] libnyx plugin is ready!
thread '<unnamed>' panicked at src/ffi.rs:97:5:
assertion `left == right` failed
  left: false
 right: true
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
             at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/panicking.rs:342:17
   3: core::panicking::assert_failed
   4: nyx_config_set_input_buffer_size
   5: afl_fsrv_start
             at ./AFLplusplus/src/afl-forkserver.c:590:5
   6: afl_fsrv_get_mapsize
             at ./AFLplusplus/src/afl-forkserver.c:1688:3
   7: main
             at ./AFLplusplus/src/afl-showmap.c:1575:9
   8: __libc_start_main
   9: _start
```

I suggest we keep the `MAX_FILE` behavior in case `fsrv->max_length == 0`. Cc @nj00001

**Comment by domenukk** [comment]
Potentially we should set up max_length in showmap as well, instead?

**Comment by choller** [comment]
@domenukk Happy to test a patch for this. I don't know where this is normally set.

**Comment by vanhauser-thc** [comment]
Why not setting MAX_FILE in the forkserver init? That’s where it would belong imho
