### ISSUE TITLE
bad free

### ISSUE THREAD

**Issue by vanhauser-thc** [AFLplusplus/AFLplusplus#520]
this is with `make CFLAGS=-g ASAN_BUILD=1`
and then `./afl-fuzz -i in -o out -- ./test-instr` and contol-c after a few seconds run time:

```
+++ Testing aborted by user +++
=================================================================
==1023239==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x606000000208 in thread T0
    #0 0x7ffff767a277 in __interceptor_free (/lib/x86_64-linux-gnu/libasan.so.5+0x107277)
    #1 0x55555557adb1 in DFL_ck_free include/alloc-inl.h:117
    #2 0x55555557ff01 in destroy_extras src/afl-fuzz-extras.c:630
    #3 0x55555557a5db in main src/afl-fuzz.c:1485
    #4 0x7ffff6e85cc9 in __libc_start_main ../csu/libc-start.c:308
    #5 0x55555556ca79 in _start (/prg/AFLplusplus/branches/dev/afl-fuzz+0x18a79)

0x606000000208 is located 8 bytes inside of 64-byte region [0x606000000200,0x606000000240)
allocated by thread T0 here:
    #0 0x7ffff767aa2e in __interceptor_realloc (/lib/x86_64-linux-gnu/libasan.so.5+0x107a2e)
    #1 0x55555557afc0 in afl_realloc include/alloc-inl.h:697
    #2 0x55555557e45d in add_extra src/afl-fuzz-extras.c:390
    #3 0x5555555e5fee in afl_fsrv_start src/afl-forkserver.c:718
    #4 0x5555555cb0a7 in calibrate_case src/afl-fuzz-run.c:334
    #5 0x555555583bc6 in perform_dry_run src/afl-fuzz-init.c:773
    #6 0x55555557900b in main src/afl-fuzz.c:1237
    #7 0x7ffff6e85cc9 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: bad-free (/lib/x86_64-linux-gnu/libasan.so.5+0x107277) in __interceptor_free
==1023239==ABORTING
```

backtrace --- it is in the code you changed.

**Comment by vanhauser-thc** [comment]
@domenukk this affects stable

**Comment by domenukk** [comment]
The new afl_realloc needs to be freed with afl_free as the returned pointer is not the beginning of the actually allocated datastructure. Instead, we store the size in the beginning.
5ec91fce should fix this, can you try again?
This should not pose a severe problem for stable I don't think.

**Comment by domenukk** [comment]
Don't we have an ASAN build in one of our test cases? If not, we should add it.
