### ISSUE TITLE
shared_buf and shared_buf_len of afl-qemu-cpu-inl.h are sometimes not initialized which leads to a crash

### ISSUE THREAD

**Issue by jockiejackie** [AFLplusplus/AFLplusplus#597]
Hey guys! I've stumbled upon an interesting crash which occurs in afl++ when using qemu mode with persistent hook. It happens on both stable and dev branches. Unfortunately, I cannot share a harness or target application, but will do my best to describe this issue.

So, my harness is x86, hooked function has prototype of `__attribute__((fastcall)) void harnessFunc(unsigned char *data, size_t size)` and has a single exit point. The code in coverage of which is loaded dynamically at known range so I specify it with AFL_CODE_START and AFL_CODE_END.

I've noticed that when I supply fuzzer with specific input it crashes during dry run, however it doesn't happen if I run harness against this file manually.

To investigate, I've run harness against this "bad input" using `afl-qemu-trace` and gdb:

```
$ gdb afl-qemu-trace
...
(gdb) set environment AFL_CODE_START 0x1000000 // the code I fuzz is loaded at specific range and I specify it using these env vars
(gdb) set environment AFL_CODE_END 0x1010000
(gdb) set environment AFL_QEMU_PERSISTENT_ADDR 0xFFF2262C // start of function in harness which should be looped
(gdb) set environment AFL_QEMU_PERSISTENT_RET 0xFFF226FD // end of that function
(gdb) set environment AFL_QEMU_PERSISTENT_GPR 1
(gdb) set environment AFL_QEMU_PERSISTENT_HOOK ./read_into_ecx_edx.so
(gdb) set environment AFL_QEMU_DEBUG_MAPS 1

(gdb) r ./harness ./in/bad-input
...
I see that harness did init and was about to call harnessFunc with data of bad-input
...

Thread 1 "afl-qemu-trace" received signal SIGSEGV, Segmentation fault.
0x000055555563e860 in callback_to_persistent_hook () at /home/user/AFLplusplus/qemu_mode/qemu-3.1.1/../patches/afl-qemu-cpu-translate-inl.h:164
164       afl_persistent_hook_ptr(persistent_saved_gpr, guest_base, shared_buf,
(gdb) bt
#0  0x000055555563e860 in callback_to_persistent_hook () at /home/user/AFLplusplus/qemu_mode/qemu-3.1.1/../patches/afl-qemu-cpu-translate-inl.h:164
#1  0x00005555569d7698 in static_code_gen_buffer ()
#2  0x00005555556010cc in cpu_tb_exec (itb=<optimized out>, cpu=0x5555569d7540 <static_code_gen_buffer+17113936>) at /home/user/AFLplusplus/qemu_mode/qemu-3.1.1/accel/tcg/cpu-exec.c:173
#3  cpu_loop_exec_tb (tb_exit=<synthetic pointer>, last_tb=<synthetic pointer>, tb=<optimized out>, cpu=0x5555569d7540 <static_code_gen_buffer+17113936>) at /home/user/AFLplusplus/qemu_mode/qemu-3.1.1/accel/tcg/cpu-exec.c:623
#4  cpu_exec (cpu=cpu@entry=0x5555579b4d40) at /home/user/AFLplusplus/qemu_mode/qemu-3.1.1/accel/tcg/cpu-exec.c:733
#5  0x0000555555635370 in cpu_loop (env=0x5555579bcff0) at /home/user/AFLplusplus/qemu_mode/qemu-3.1.1/linux-user/i386/cpu_loop.c:93
#6  0x00005555555c33bc in main (argc=<optimized out>, argv=0x7fffffffe248, envp=<optimized out>) at /home/user/AFLplusplus/qemu_mode/qemu-3.1.1/linux-user/main.c:819

(gdb) x/10i $rip
=> 0x55555563bc9c <callback_to_persistent_hook+28>:     mov    ecx,DWORD PTR [rax]
   0x55555563bc9e <callback_to_persistent_hook+30>:     jmp    QWORD PTR [rip+0x522b3c]        # 0x555555b5e7e0 <afl_persistent_hook_ptr>

(gdb) info registers
rax            0x0      0
rbx            0x555555b5e858   93824998565976
rcx            0x0      0
rdx            0x0      0
rsi            0x7ffef0001000   140732924956672
rdi            0x555555b5e820   93824998565920
rbp            0xfff1efe4       0xfff1efe4
rsp            0x7fffffffd248   0x7fffffffd248
r8             0x555556bccc80   93825015794816
r9             0x555557baa8e0   93825032431840
r10            0x0      0
r11            0x0      0
r12            0x555557bae130   93825032446256
r13            0x555556bcce80   93825015795328
r14            0x555557bae130   93825032446256
r15            0x555556bccc80   93825015794816
rip            0x55555563bc9c   0x55555563bc9c <callback_to_persistent_hook+28>
```

Looked up `callback_to_persistent_hook` function in IDA and matched with register values I saw in gdb:
```
; void __cdecl callback_to_persistent_hook()
callback_to_persistent_hook proc near
; __unwind {
mov     rax, cs:shared_buf_len    // 0
mov     rdx, cs:shared_buf        // 0
lea     rdi, persistent_saved_gpr // 0x555555b5e820
mov     rsi, cs:guest_base        // 0x7ffef0001000
mov     ecx, [rax]                // <-- crash over here, rax is NULL
jmp     cs:afl_persistent_hook_ptr
```

Sooo, it looks like `shared_buf` and `shared_buf_len` might be uninitialized and I'm not familiar enough with Qemu to spot a codepath which might cause that.

It looks very weird that this crash depends on input data because it occurs BEFORE any processing of this data. How do I know? Added `int 3` to the very start of `harnessFunc`. If it would be hited, I would see something like `qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped` (checked by moving `int 3` to an earlier executed code).

I've also tried dev branch and the behavior is slightly different, the crash occurs in the middle of second or the start of third call of `harnessFunc` according to printfs (I did `setbuf(stdout, NULL);` but still can't be quite sure):
```
Thread 1 "afl-qemu-trace" received signal SIGSEGV, Segmentation fault.
0x00007fffe818cb32 in code_gen_buffer ()
(gdb) bt
#0  0x00007fffe818cb32 in code_gen_buffer ()
#1  0x000055555569dbe7 in cpu_tb_exec (itb=<optimized out>, cpu=0x555555bf9370) at ../accel/tcg/cpu-exec.c:1099
#2  cpu_loop_exec_tb (tb_exit=<synthetic pointer>, last_tb=<synthetic pointer>, tb=<optimized out>, cpu=0x555555bf9370) at ../accel/tcg/cpu-exec.c:1570
#3  cpu_exec (cpu=cpu@entry=0x555555bf9370) at ../accel/tcg/cpu-exec.c:1683
#4  0x00005555555d62a8 in cpu_loop (env=0x555555c01640) at ../linux-user/i386/cpu_loop.c:209
#5  0x00005555555cdc5a in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at ../linux-user/main.c:863
(gdb) x/10i $rip
=> 0x7fffe818cb32 <code_gen_buffer+1624837>:    mov    r12d,DWORD PTR gs:[rbx]
   0x7fffe818cb36 <code_gen_buffer+1624841>:    mov    r13d,DWORD PTR [rbp+0x1c]
   0x7fffe818cb3a <code_gen_buffer+1624845>:    mov    DWORD PTR gs:[r13+0x0],r12d
   0x7fffe818cb3f <code_gen_buffer+1624850>:    mov    r12d,DWORD PTR [rbp+0x38]
   0x7fffe818cb43 <code_gen_buffer+1624854>:    shl    r12d,0x2
   0x7fffe818cb47 <code_gen_buffer+1624858>:    add    ebx,r12d
   0x7fffe818cb4a <code_gen_buffer+1624861>:    mov    DWORD PTR [rbp+0x18],ebx
   0x7fffe818cb4d <code_gen_buffer+1624864>:    lea    ebx,[r13+r12*1+0x0]
   0x7fffe818cb52 <code_gen_buffer+1624869>:    mov    DWORD PTR [rbp+0x1c],ebx
   0x7fffe818cb55 <code_gen_buffer+1624872>:    mov    ebx,DWORD PTR [rbp+0x4]
(gdb) info registers
rax            0x7fffe811f500   140737086878976
rbx            0x3f7c8d27       1065127207
rcx            0x0      0
rdx            0x555555bcc6dc   93824999016156
rsi            0x0      0
rdi            0x555555bf9370   93824999199600
rbp            0x555555c01640   0x555555c01640
rsp            0x7fffffffd200   0x7fffffffd200
r8             0xff000000       4278190080
r9             0x0      0
r10            0x3fffe450       1073734736
r11            0x3fffe4bc       1073734844
r12            0x0      0
r13            0x3f7c8d27       1065127207
r14            0x3fffe3c4       1073734596
r15            0x1000   4096
rip            0x7fffe818cb32   0x7fffe818cb32 <code_gen_buffer+1624837>
```

Dunno how to check with gdb whether `gs:[rbx]` is mapped and readable.

Any idea what might be going wrong? :)

P.S. Launching afl-fuzz against another corpus (actually a single file with phrase "hello", haha) produced ~800 crashes (~90 unique) for 4M runs with none of them being reproducible. Maybe this is just this bug triggering.

Upd: I've added logging to `callback_to_persistent_hook` in case shared_buf or shared_buf_len are null and it's not hit when I get crashes during fuzzing. Seems like crashes are fair and I can't repro them because actual corruption is made by some previous testcase and it's not caught because of lack of ASAN.

**Comment by vanhauser-thc** [comment]
@jockiejackie can you please supply everything needed to reproduce this? the target, your module, the exact commandline etc.
thank you!

@andreafioraldi

**Comment by jockiejackie** [comment]
@vanhauser-thc, sorry, I can't share anything to reproduce this.

**Comment by vanhauser-thc** [comment]
@jockiejackie  I know that @andreafioraldi tested the persistent hook because he sent around a screenshot of the performance in our private chat. So I know he tested it and it works for him. 
So - if you cannot submit any setup that we can use to reproduce it (maybe code your own C code harness that works similar to your target in a few lines?) I am not sure we will be able to find and fix this. especially as it could be that the issue might be that your persistent hook .so changes might be the issue here - that further reduces the motivation to invest a lot of time ...

**Comment by andreafioraldi** [comment]
Can u at least share your persistent hook module? If you don't specify that u want the input from shared mem, the default is stdin.

https://github.com/AFLplusplus/AFLplusplus/blob/stable/examples/qemu_persistent_hook/read_into_rdi.c#L31

You have to return 1 from afl_persistent_hook_init, this is documented in the readme too.

**Comment by andreafioraldi** [comment]
Oh you are using qemu 3, update it the persistent hook has not a regs struct.

**Comment by jockiejackie** [comment]
read_into_ecx_edx.c:
```
#include <stdint.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>

#define g2h(x) ((void *)((unsigned long)(x) + guest_base))
#define h2g(x) ((uint64_t)(x)-guest_base)

enum {

  R_EAX = 0,
  R_ECX = 1,
  R_EDX = 2,
  R_EBX = 3,
  R_ESP = 4,
  R_EBP = 5,
  R_ESI = 6,
  R_EDI = 7,
  R_R8 = 8,
  R_R9 = 9,
  R_R10 = 10,
  R_R11 = 11,
  R_R12 = 12,
  R_R13 = 13,
  R_R14 = 14,
  R_R15 = 15,

  R_AL = 0,
  R_CL = 1,
  R_DL = 2,
  R_BL = 3,
  R_AH = 4,
  R_CH = 5,
  R_DH = 6,
  R_BH = 7,

};

void afl_persistent_hook(uint64_t *regs, uint64_t guest_base,
                         uint8_t *input_buf, uint32_t input_len) {

  // In this example the register ECX pointing to the memory location
  // of the target buffer, and the length of the input is in EDX.
  // This can be seen with a debugger, e.g. gdb (and "disass main")

  // printf("placing input into %p\n", regs[R_ECX]);

  // if (input_len > 1024) input_len = 1024;
  memcpy(g2h(regs[R_ECX]), input_buf, input_len);
  regs[R_EDX] = input_len;

}

int afl_persistent_hook_init(void) {

  // 1 for shared memory input (faster), 0 for normal input (you have to use
  // read(), input_buf will be NULL)
  return 1;
}

```

```
__attribute__((fastcall)) void harnessFunc(unsigned char *data, size_t size) {
     printf("harnessFunc started\n");
     // call fuzzed binary function which does actual parsing
     foobar(data, size);
     printf("harnessFunc finished\n");
}
```

**Comment by andreafioraldi** [comment]
Closed because this part was redesigned for qemu 5.
